os:
- linux
- osx
language: go
addons:
  artifacts:
    paths:
    - maputnik
install:
- nvm install 6
- nvm use 6
- go get github.com/fsnotify/fsnotify
- go get github.com/gorilla/handlers
- go get github.com/gorilla/mux
- go get github.com/gorilla/websocket
- go get github.com/urfave/cli
- go get github.com/elazarl/go-bindata-assetfs/...
- go get github.com/jteeuwen/go-bindata/...
script:
- mkdir -p editor/public
- make
