language: node_js
addons:
  firefox: latest
matrix:
  - include:
    - os: linux
      env: CXX=g++-4.8
    - os: osx
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
install:
  - npm install
script:
  - mkdir public
  - node --stack_size=100000 $(which npm) run build
  - npm run lint
  - npm run lint-styles
  - npm run test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
