os:
- linux
language: go
go:
- 1.11.x
addons:
  artifacts:
    paths:
    - bin
install:
- wget https://raw.githubusercontent.com/openmaptiles/klokantech-basic-gl-style/master/style.json
script:
- make
- ./bin/linux/maputnik --help
- ./bin/linux/maputnik --version
- ./bin/linux/maputnik --watch --file style.json & sleep 5; kill $!
