os:
- linux
language: go
go:
- 1.14.x
addons:
  artifacts:
    paths:
    - bin
install:
- wget https://maputnik.github.io/osm-liberty/style.json
script:
- make
- ./bin/linux/maputnik --help
- ./bin/linux/maputnik --version
- ./bin/linux/maputnik --watch --file style.json & sleep 5; kill $!
