environment:
  nodejs_version: "5.11"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test
