# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\maputnik\desktop

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version
- go env
- go get github.com/fsnotify/fsnotify
- go get github.com/gorilla/handlers
- go get github.com/gorilla/mux
- go get github.com/gorilla/websocket
- go get github.com/urfave/cli
- go get github.com/elazarl/go-bindata-assetfs/...
- go get github.com/jteeuwen/go-bindata/...

# to run your custom scripts instead of automatic MSBuild
build_script:
- go vet ./...
- gofmt -s -l .
- C:\MinGW\bin\mingw32-make.exe

# to disable automatic tests
test: off

# to disable deployment
deploy: off
