name: deploy

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'

jobs:
  # publish docker to GitHub registry
  deploy-docker:
    name: deploy/docker
    runs-on: ${{ matrix.os }}

    if: ${{ github.event_name == 'push' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - run: docker build -t ghcr.io/maplibre/maputnik:main .
    - run: docker push ghcr.io/maplibre/maputnik:main
